### ISSUE TITLE
Move top_10 counting code  `blogs/views.py` code back into redactors

### ISSUE THREAD

**Issue by enoren5** [enoren5/CC_Redact_Iter3#6]
Right now inside `blogs/views.py`, there is one function. Lines 6-23 run as intended. However lines 25-33 need to be moved into `wordcounters/views.py`. Moving lines 25-33 into the `wordcounters` app will require moving utils.py as well. The functionality needs to be preserved after the shuffle.

**Comment by UmarGit** [comment]
### Hey @enoren5 ,

> I need a little help, regarding this issue. As we have a post ( blog post ) data and alice text data. When we move the top_counter mechanism the top 10 word will be count from both of the blog post and alice text or one of them ?

**_Thank you_**

**Comment by enoren5** [comment]
Umar Ahmed resolves this Issue in PR #15
